import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const grid = readFileSync(resolve(root, 'src/components/Layout/WorkspaceGrid.tsx'), 'utf8');
const css = readFileSync(resolve(root, 'src/App.css'), 'utf8');

function includesAll(source, values) {
  for (const value of values) assert.ok(source.includes(value), `missing ${value}`);
}

includesAll(grid, [
  'className="td-workspace-tab-add"',
  'ref={addButtonRef}',
  'ref={firstAddMenuItemRef}',
  'const addMenuId = useId();',
  'const openAddMenu = useCallback(() =>',
  'const handleAddButtonKeyDown = useCallback((event: React.KeyboardEvent<HTMLButtonElement>) =>',
  "if (event.key !== 'ArrowDown') return;",
  'openAddMenu();',
  'aria-label="Open new pane tab"',
  'onKeyDown={handleAddButtonKeyDown}',
  'aria-controls={addMenuOpen ? addMenuId : undefined}',
  '<div id={addMenuId} className="td-agent-add-menu td-workspace-tab-add-menu"',
  'role="menu" aria-label="New workspace pane"',
  'role="tablist" aria-label="Workspace panes"',
  'role="tab"',
  'const paneTabIdPrefix = useId();',
  'id={`${paneTabIdPrefix}-tab-${pane.id}`}',
  'aria-selected={activePane?.id === pane.id}',
  'aria-controls={`${paneTabIdPrefix}-panel-${pane.id}`}',
  'role="tabpanel"',
  'aria-labelledby={activePaneTabId}',
  'id={activePanePanelId}',
  'onKeyDown={(event) => handlePaneTabKeyDown(event, pane.id, index)}',
  'if (event.target !== event.currentTarget) return;',
  'const tabButtonRefs = useRef(new Map<string, HTMLDivElement>());',
  "['ArrowLeft', 'ArrowRight', 'Home', 'End']",
  'tabButtonRefs.current.get(nextPane.id)?.focus();',
  'onKeyDown={(e) => e.stopPropagation()}',
  'focus-visible:opacity-100',
  'onKeyDown={handleAddMenuKeyDown}',
  "['ArrowDown', 'ArrowUp', 'Home', 'End']",
  '<ClipboardPenLine size={14} />',
  '<TerminalSquare size={14} />',
  '<Globe2 size={14} />',
  '<span>Editor</span>',
  '<span>Terminal</span>',
  '<span>Server</span>',
  'aria-label={`${secondaryPaneId === pane.id ? \'Close split view for\' : \'Open to side\'} ${pane.title}`}',
  'aria-label={`Close ${pane.title}`}',
  'type="button"\n                  onClick={(e) => { e.stopPropagation(); toggleSplitPane(pane.id); }}',
  'type="button"\n                onClick={(e) => {',
  'type="button"\n              onMouseDown={(e) => e.stopPropagation()}',
  'No running servers found',
  'detectedServers.length === 1',
  'detectedServers.length} running servers found',
  'detectedServers.map(server =>',
  'const openServerPane = useCallback((server: DetectedWorkspaceServer) =>',
  'normalizePreviewUrl(server.url)',
  'const existingServerPane = panes.find(pane => (',
  'activatePane(existingServerPane.id);',
  '`Server: ${shortWorkspaceServerUrl(server.url)}`',
  '}, [activatePane, addPane, panes]);',
  'td-workspace-tab-add-heading',
  'aria-label="Create editor pane"',
  'aria-label="Create terminal pane"',
  'onClick={() => openServerPane(server)}',
  'aria-label={`Open server ${formatWorkspaceServerLabel(detectedServers[0])}`}',
  'aria-label={`Open server ${formatWorkspaceServerLabel(server)}`}',
  'title={shortWorkspaceServerUrl(detectedServers[0].url)}',
  'title={shortWorkspaceServerUrl(server.url)}',
  'aria-label={`${detectedServers.length} running servers found`}',
  'className="td-workspace-tab-add-heading" role="presentation" aria-hidden="true"',
  "import { normalizeTerminalId } from '../../lib/terminalIds';",
  'normalizeTerminalId(pane.data?.terminalId)',
  'Array.from(new Set(panes',
  'interface WorkspacePaneDropDetail',
  'const WORKSPACE_PANE_DROP_TYPES = new Set<PaneType>([',
  'WORKSPACE_PANE_DROP_TYPES.has(detail.type as PaneType)',
  'isWorkspacePaneDropDetail',
  'containerWidth <= 0',
  'if (!addMenuOpen || terminalIds.length === 0) return;',
  '}, [addMenuOpen, terminalIds]);',
]);

includesAll(readFileSync(resolve(root, 'src/store/workspace.ts'), 'utf8'), [
  'function activeWorkspaceDirForState(state: WorkspaceState): string | null',
  'function cleanPaneDataInput(data: unknown): Record<string, unknown>',
  'Object.entries(data as Record<string, unknown>).filter(([, value]) => value !== undefined)',
  'function paneDataWithActiveWorkspaceDir(state: WorkspaceState, data?: any): any',
  'const EMPTY_PANES: Pane[] = [];',
  'function safePanes(value: unknown): Pane[]',
  'if (!Array.isArray(value)) return EMPTY_PANES;',
  'return value.filter(isPane);',
  'return value;',
  'function normalizeSavedLayoutPane(value: unknown): Pick<Pane, \'type\' | \'title\' | \'data\' | \'gridPos\'> | null',
  'data: cleanPaneDataInput(pane.data)',
  'gridPos: normalizeGridPos(pane.gridPos, { x: 0, y: 0, w: 25, h: 40 })',
  'const layoutPanes = Array.isArray(layout.panes)',
  'layout.panes.map(normalizeSavedLayoutPane).filter((pane): pane is Pick<Pane, \'type\' | \'title\' | \'data\' | \'gridPos\'> => Boolean(pane))',
  'return safePanes(panes);',
  'updater(safePanes(t.panes))',
  'panes: safePanes(tab.panes).filter(pane => pane.type !== \'editor\')',
  'panes: safePanes(tab.panes).map(p =>',
  'panes: safePanes(tab.panes).map(pane =>',
  'panes: safePanes(tab.panes).filter(p => p.type !== \'terminal\').map(p =>',
  'const tabs = Array.isArray(persistedState?.tabs) ? persistedState.tabs : []',
  'panes: (Array.isArray(tab.panes) ? tab.panes : []).map((pane: any, idx: number) =>',
  'persistedState = { ...persistedState, tabs: updatedTabs };',
  'persistedState = {',
  'panes: (Array.isArray(tab.panes) ? tab.panes : []).map((pane: any) =>',
  'panes: (Array.isArray(tab.panes) ? tab.panes : [])',
  'export function cleanWorkspaceTabName(value: unknown, fallback = \'Workspace\'): string',
  'export function cleanSavedLayoutName(value: unknown, fallback = \'Workspace layout\'): string',
  'name: cleanWorkspaceTabName(name, t.name)',
  'name: cleanSavedLayoutName(name)',
  'title: cleanPaneTitle(title, type === \'terminal\' ? \'Terminal\' : \'Untitled\')',
  'title: cleanPaneTitle(p.title, p.type === \'terminal\' ? \'Terminal\' : \'Untitled\')',
  'data: cleanPaneDataInput(data)',
  'gridPos: normalizeGridPos(gridPos, { x: 0, y: 0, w: 25, h: 40 })',
  'const nextData = cleanPaneDataInput(data);',
  'const providedWorkspaceDir = cleanWorkspaceDirValue(typeof nextData.workspaceDir === \'string\' ? nextData.workspaceDir : null);',
  'nextData.workspaceDir = providedWorkspaceDir;',
  'delete nextData.workspaceDir;',
  'workspaceDir: activeWorkspaceDir,',
  'const newData = paneDataForType(state, type, data);',
  'data: paneDataWithActiveWorkspaceDir(state, { terminalId: generateId() })',
]);

includesAll(css, [
  '.td-workspace-tab-add',
  '.td-workspace-tab-add-menu',
  '.td-workspace-tab-add-server-list',
  '.td-workspace-tab-add-server-list .td-agent-add-option',
  '.td-workspace-tab-add-heading',
  '.td-workspace-tab-add-heading > svg',
  'width: min(260px, calc(100vw - 24px));',
  'flex: 1 1 auto;',
  '.td-agent-add-option > svg',
  'flex: 0 0 auto;',
  'min-width: 0;',
  'padding-left: 25px;',
  '.td-agent-add-option:hover',
]);

console.log('PASS workspace tab add menu exposes accessible Editor, Terminal, and running-server actions');
